INSERT INTO USER(ID, USERNAME, PASSWORD, STATUS) VALUES (1, 'user1@test.com', '$2a$12$f9SyUPCHpVnPjBEs3CB3LeCzp7SVQw9dXXI.Da4nUNAmYKn.OGMei', 1);
INSERT INTO USER(ID, USERNAME, PASSWORD, STATUS) VALUES (2, 'user2@test.com', '$2a$12$f9SyUPCHpVnPjBEs3CB3LeCzp7SVQw9dXXI.Da4nUNAmYKn.OGMei', 1);
INSERT INTO USER(ID, USERNAME, PASSWORD, STATUS) VALUES (3, 'user3@test.com', '$2a$12$f9SyUPCHpVnPjBEs3CB3LeCzp7SVQw9dXXI.Da4nUNAmYKn.OGMei', 1);
INSERT INTO USER(ID, USERNAME, PASSWORD, STATUS) VALUES (4, 'user4@test.com', '$2a$12$f9SyUPCHpVnPjBEs3CB3LeCzp7SVQw9dXXI.Da4nUNAmYKn.OGMei', 0);
INSERT INTO USER(ID, USERNAME, PASSWORD, STATUS) VALUES (5, 'user5@test.com', '$2a$12$f9SyUPCHpVnPjBEs3CB3LeCzp7SVQw9dXXI.Da4nUNAmYKn.OGMei', 0);

INSERT INTO OPERATION(ID, TYPE, COST) VALUES (1, 'A', 1);
INSERT INTO OPERATION(ID, TYPE, COST) VALUES (2, 'S', 1);
INSERT INTO OPERATION(ID, TYPE, COST) VALUES (3, 'M', 1);
INSERT INTO OPERATION(ID, TYPE, COST) VALUES (4, 'D', 1);
INSERT INTO OPERATION(ID, TYPE, COST) VALUES (5, 'SR', 1);
INSERT INTO OPERATION(ID, TYPE, COST) VALUES (6, 'RS', 1);
